### ISSUE TITLE
Invalid KQL for Sentinel | endpoints-associated-with-multiple-deviceids

### ISSUE THREAD

**Issue by Marshyp** [cyb3rmik3/KQL-threat-hunting-queries#1]
On the endpoints-associated-with-multiple-deviceids (https://github.com/cyb3rmik3/KQL-threat-hunting-queries/blob/main/03.SecOps/endpoints-associated-with-multiple-deviceids.md) query for Sentinel, the query gives an error of: 

> Query could not be parsed at 'DeviceInfo' on line [1,14]
> 
> Token: DeviceInfo
> Line: 1
> Position: 14
> Request id: 0d6c2678-a10c-4c1b-a156-7eb618053b2f

**Comment by cyb3rmik3** [comment]
You are right, @Marshyp. Following your comment, it turns out the Microsoft 365 query works as expected now, however the results don't match the Sentinel's hence I will look into it and revert.

**Comment by Marshyp** [comment]
> You are right, @Marshyp. Following your comment, it turns out the Microsoft 365 query works as expected now, however the results don't match the Sentinel's hence I will look into it and revert.

Thanks @cyb3rmik3 - I tried to have a quick look yesterday but as is typical, the metaphorical hit the fan…!
Hopefully I’ll have some time over the coming days to take a proper look.

Appreciate your assistance!

**Comment by cyb3rmik3** [comment]
Hi @Marshyp sorry for super late reply, I tried the queries and they are both working as expected. Can you please confirm from your side as well?
